---
ID: "efcf33ee-8667-42c5-b6b5-08b59fcdf0a2"
Parent: "63a9839a-3342-4abb-b183-8368283f8e5b"
Template: "63a9839a-3342-4abb-b183-8368283f8e5b"
Path: /sitecore/templates/Project/Corporate/Datasources/Description with stats/Stats/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/list_style_numbered.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231005T032440Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "75ce934a-e9f5-4d52-bfde-3fb97ca5fd86"
      Hint: StatDescription
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "715d1265-525c-4a9c-9099-a7cb607c5031"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240110T031307Z
