---
ID: "7a5493ff-b1ba-4731-bcc7-fa27c5aa572f"
Parent: "197552ec-ddf6-45b4-b5fc-9524333eaf7c"
Template: "197552ec-ddf6-45b4-b5fc-9524333eaf7c"
Path: /sitecore/templates/Project/Corporate/Datasources/Content/Two Columns Video/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231017T035412Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a96e373f-0d8a-4790-8a6b-c29b0ba3921b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dpham@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231017T035412Z
