---
ID: "c0cf78dd-b053-40f3-b72d-264a45b8bb5d"
Parent: "fcf005b9-10ee-4d09-830f-cb7333733c96"
Template: "fcf005b9-10ee-4d09-830f-cb7333733c96"
Path: /sitecore/templates/Project/Perskindol/Datasources/Product/Product Detail Content/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{5BC35C59-0904-4C62-A2A6-4DA65D41899F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231106T082513Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f45a17f7-be6e-42b7-af42-c337bedaea87"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231106T082617Z
