---
ID: "6c9ee8a1-0c7b-43dc-a8a4-3b63127b37a4"
Parent: "2515b3f1-ef1c-4566-b8af-f8a1fca3f646"
Template: "2515b3f1-ef1c-4566-b8af-f8a1fca3f646"
Path: /sitecore/templates/Project/Propan/Datasources/Common/Footer/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240206T041202Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b4d27f0f-10ea-4ed9-b5c8-7ae8584b4463"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240206T041310Z
