---
ID: "557d29bc-8f7f-43a6-820a-81c48fc3afda"
Parent: "5e4a7ddd-3841-4b7b-8851-d9f6c52031a3"
Template: "5e4a7ddd-3841-4b7b-8851-d9f6c52031a3"
Path: /sitecore/templates/Project/OneZP/Datasources/My Apps/Application Details/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231227T072308Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "54a44bcc-4ca8-4cfe-9ad0-9795d1d9e18c"
      Hint: ApplicationName
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a51a7113-f442-4f57-ae98-eb10e0ba4372"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ngunguyen@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240130T035237Z
