---
ID: "2e3606a1-9950-4635-87b4-bca0fb848eb8"
Parent: "fc7c1c87-c24d-4982-a25b-057bbb0f1d31"
Template: "fc7c1c87-c24d-4982-a25b-057bbb0f1d31"
Path: /sitecore/templates/Project/Perskindol/Datasources/Product/Product Pain Type Content/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3C59A717-A689-4798-BF3A-2EDAA4CB15A6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231107T091855Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a64de8fd-0cbc-402e-8023-06eed62157fa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231107T091942Z
