---
ID: "8b7e3215-675c-414d-b008-f4de436532f2"
Parent: "da2d7e43-fbfe-46a5-865b-1cdab371a60c"
Template: "da2d7e43-fbfe-46a5-865b-1cdab371a60c"
Path: /sitecore/templates/Project/Perskindol/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {DA2D7E43-FBFE-46A5-865B-1CDAB371A60C}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231025T091659Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac4f8e06-780b-4e61-bbe1-634cdbee5cd1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hta@zuelligpharma.com
    - ID: "c21d85ec-2219-46b9-b4d9-f72750a0bed3"
      Hint: Title
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231025T091705Z
